### ISSUE TITLE
Number of causal SNPs

### ISSUE THREAD

**Issue by daria-nikanorova** [variani/finemapr#12]
Hello and thank you for your tool!

Could you please explain, how the number of causal SNPs for FINEMAP is chosen in your implementation?

**Comment by variani** [comment]
Hi,

Your question is more related to the FINEMAP method itself rather than my package. When I was running FINEMAP, the default value for the maximum number of causal SNPs was 5 (that might be changed in the current version of FINEMAP). Obviously, you can specify a number >5.

Again, I would suggest to run FINEMAP directly and avoid using my package because I've stopped using/maintaining it.

Best,
Andrey
